import { defaultImages } from './defaultImages';

export const events = [
  {
    title: 'Galery Opening',
    text: 'Discover an enchanting evening celebrating the world of art at our exclusive gallery opening.',
    imagex1: defaultImages.img1x1,
    imagex2: defaultImages.img1x2,
    description: 'art',
    id: 1,
    category: 'Art',
    priority: 'High',
    location: 'Kyiv',
    date: '12.07',
    time: '12:00',
  },
  {
    title: 'Innovation Summit',
    text: 'Engage in a thought-provoking journey of knowledge and collaboration at our Innovation Summit. ',
    imagex1: defaultImages.img2x1,
    imagex2: defaultImages.img2x2,
    description: 'summit',
    id: 2,
    category: 'Conference',
    priority: 'Medium',
    location: 'Kyiv',
    date: '12.07',
    time: '12:00',
  },
  {
    title: 'Empower Your Creativity',
    text: 'Ignite your creativity and nurture your storytelling skills in our immersive Creative Writing Workshop. ',
    imagex1: defaultImages.img3x1,
    imagex2: defaultImages.img3x2,
    description: 'immersive',
    id: 3,
    category: 'Workshop',
    priority: 'High',
    location: 'Kyiv',
    date: '12.07',
    time: '12:00',
  },
  {
    title: 'Summer Soiree',
    text: 'Embrace the tropical vibes and escape to paradise at our Beach Luau Extravaganza.',
    imagex1: defaultImages.img4x1,
    imagex2: defaultImages.img4x2,
    description: 'dinner',
    id: 4,
    category: 'Party',
    priority: 'Medium',
    location: 'High',
    date: '12.07',
    time: '12:00',
  },
  {
    title: 'Leadership Conference',
    text: 'Unlock the secrets of effective leadership at our transformative Success Leadership Conference.',
    imagex1: defaultImages.img5x1,
    imagex2: defaultImages.img5x2,
    description: 'conference',
    id: 5,
    category: 'Business',
    priority: 'Medium',
    location: 'Kyiv',
    date: '12.07',
    time: '12:00',
  },
  {
    title: 'Tech Startup Showcase',
    text: 'Witness the future of technology as innovative startups showcase their groundbreaking ideas.',
    imagex1: defaultImages.img6x1,
    imagex2: defaultImages.img6x2,
    description: 'event',
    id: 6,
    category: 'Workshop',
    priority: 'Low',
    location: 'Kyiv',
    date: '12.07',
    time: '12:00',
  },
  {
    title: 'Acoustic Garden Concert',
    text: 'Experience the magic of live music amidst the serene beauty of nature at our Acoustic Garden Concert.',
    imagex1: defaultImages.img7x1,
    imagex2: defaultImages.img7x2,
    description: 'concert',
    id: 7,
    category: 'Music',
    priority: 'High',
    location: 'Kyiv',
    date: '12.07',
    time: '12:00',
  },
  {
    title: 'Extreme Adventure Race',
    text: 'Calling all thrill-seekers! Embark on an adrenaline-pumping journey at our Extreme Adventure Race.',
    imagex1: defaultImages.img8x1,
    imagex2: defaultImages.img8x2,
    description: 'people',
    id: 8,
    category: 'Sport',
    priority: 'Low',
    location: 'Kyiv',
    date: '12.07',
    time: '12:00',
  },
];
